# Generated by Django 3.0 on 2020-07-18 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=40)),
                ('status', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(default=None, max_length=20)),
                ('perms', models.IntegerField()),
                ('team', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResetTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('time', models.DateTimeField()),
                ('status', models.BooleanField(max_length=0)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.BooleanField(default=False)),
                ('approve', models.IntegerField(default=0)),
                ('disapprove', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, default=None)),
                ('admin1', models.CharField(max_length=150)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
